name: Build and Deploy MONSTACK App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Server Dependencies
        working-directory: ./backend
        run: npm install

      - name: Create .env file for backend
        working-directory: ./backend
        run: |
          echo "PORT=5000" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

      - name: Install Client Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
